blank_issues_enabled: false
contact_links:
  - name: Последний релиз
    url: https://github.com/scarrymany/scarp-wallpaper/releases/latest
    about: Проверьте, не исправлена ли ошибка в свежей версии.
